extends: standard

overrides:
  - files: ['*.mjs', '*.js']
    rules:
      no-restricted-globals: [2, require, __dirname]
  - files: ['test/**']
    env: { mocha: true }
  - files: ['lib/**', 'lib/parsers/*']
    parserOptions: { ecmaVersion: 2015 }

ignorePatterns:
  - demo/
  - dist/
  - benchmark/extra/

rules:
  camelcase: 0
  no-multi-spaces: 0
